# Generated by Django 6.0.3 on 2026-05-18 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='quantite_vendue',
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('prix', models.FloatField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mon_stock.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mon_stock.vente')),
            ],
            options={
                'verbose_name': 'Ligne de vente',
                'verbose_name_plural': 'Lignes de vente',
            },
        ),
        migrations.AddField(
            model_name='vente',
            name='produits',
            field=models.ManyToManyField(related_name='ventes', through='mon_stock.LigneVente', to='mon_stock.produit'),
        ),
    ]
